databases:
  - name: sevent-ms-db
    plan: free
    databaseName: event_ms_db
    user: event_ms_user

services:
  - type: web
    name: sevent-ms
    runtime: docker
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/SeventMS.war
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sevent-ms-db
          property: connectionString
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: LOGGING_LEVEL_COM_EVENTMS
        value: INFO
      - key: SPRING_SQL_INIT_MODE
        value: always
      - key: SPRING_SQL_INIT_SCHEMA_LOCATIONS
        value: classpath:postgres_schema.sql
    autoDeploy: true
